  - name: prod-complete
    serial: true
    public: false
    plan:
      - aggregate:
        - get: tools
        - get: m2
        - get: repo
          passed: [ prod-deploy ]
          trigger: false
      - task: prod-complete
        file: tools/concourse/tasks/prod-complete.yml
        params:
          - _JAVA_OPTIONS: -Djava.security.egd=file:/dev/./urandom
          - GIT_EMAIL: {{git-email}}
          - GIT_NAME: {{git-name}}
          - REDOWNLOAD_INFRA: {{redownload-infra}}
          - REDEPLOY_INFRA: {{redeploy-infra}}
          - M2_SETTINGS_REPO_ID: {{m2-settings-repo-id}}
          - M2_SETTINGS_REPO_USERNAME: {{m2-settings-repo-username}}
          - M2_SETTINGS_REPO_PASSWORD: {{m2-settings-repo-password}}
          - REPO_WITH_JARS: {{snapshots-repo}}
          - REPO_WITH_JARS_INSECURE: {{repo-with-jars-insecure}}
          - M2_REPO: {{maven-local-dir}}
          - CF_PROD_USERNAME: {{cf-prod-username}}
          - CF_PROD_PASSWORD: {{cf-prod-password}}
          - CF_PROD_ORG: {{cf-prod-org}}
          - CF_PROD_SPACE: {{cf-prod-space}}
          - CF_PROD_API_URL: {{cf-prod-api-url}}
