version: "2"
services:
  jenkins:
    build:
      context: .
      args:
        gituser: "${PIPELINE_GIT_USERNAME}"
        gitpass: "${PIPELINE_GIT_PASSWORD}"
    environment:
      FORKED_REPOS: "${FORKED_REPOS}"
      EXTERNAL_IP: "${EXTERNAL_IP}"
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - /var/jenkins_home
    # links:
    #   - artifactory
  # artifactory:
  #   image: jfrog-docker-registry.bintray.io/artifactory/artifactory-oss:latest
  #   ports:
  #     - "8081:8081"
