---
resources:
 - name: repo
   type: git
   source:
     uri: {{app-url}}
     branch: {{app-branch}}
     private_key: {{github-private-key}}
 - name: version
   type: git
   source:
     uri: {{app-url}}
     branch: version
     private_key: {{github-private-key}}
 - name: tools
   type: git
   source:
     uri: {{tools-scripts-url}}
     branch: {{tools-branch}}
 - name: m2
   type: docker-image
   source:
     repository: {{docker-m2-repo}}
     email: {{docker-hub-email}}
     username: {{docker-hub-username}}
     password: {{docker-hub-password}}

jobs:
 - name: init-m2
   plan:
    - aggregate:
       - get: repo
       - get: tools
       - get: version
    - task: build-m2
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: registry.web.boeing.com/dte_replatforming/ci-pipelines:gradle3.2.1
        inputs:
         - name: repo
         - name: tools
         - name: version
        outputs:
         - name: to-push
        run:
          path: /bin/bash
          args:
           - tools/concourse/tasks/cache-m2.sh
           - init
      params:
       - M2_REPO: {{maven-local-dir}}
       - M2_SETTINGS_REPO_ID: {{m2-settings-repo-id}}
       - M2_SETTINGS_REPO_USERNAME: {{m2-settings-repo-username}}
       - M2_SETTINGS_REPO_PASSWORD: {{m2-settings-repo-password}}
    - put: m2
      params:
        import_file: to-push/rootfs.tar
 - name: update-m2
   plan:
    - aggregate:
       - get: repo
       - get: tools
       - get: m2
    - task: build-m2
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: registry.web.boeing.com/dte_replatforming/ci-pipelines:gradle3.2.1
        inputs:
         - name: repo
         - name: tools
         - name: m2
        outputs:
         - name: to-push
        run:
          path: /bin/bash
          args:
            - tools/concourse/tasks/cache-m2.sh
      params:
       - M2_REPO: {{maven-local-dir}}
       - M2_SETTINGS_REPO_ID: {{m2-settings-repo-id}}
       - M2_SETTINGS_REPO_USERNAME: {{m2-settings-repo-username}}
       - M2_SETTINGS_REPO_PASSWORD: {{m2-settings-repo-password}}
    - put: m2
      params:
        import_file: to-push/rootfs.tar
