---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: registry.web.boeing.com/dte_replatforming/ci-pipelines
    tag: "gradle3.2.1"
    insecure_registries: ["registry.web.boeing.com"]
inputs:
  - name: version
  - name: tools
  - name: repo
outputs:
  - name: out
run:
  path: /bin/bash
  args:
    - tools/concourse/tasks/generate-version.sh
